# Copyright 2020 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM golang:1.14-alpine3.11

RUN apk add --no-cache curl make

# curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
ENV KB_VERSION 2.3.1

ENV KUBEBUILDER_ASSETS /kubebuilder
ENV CGO_ENABLED 0

RUN mkdir -p ${KUBEBUILDER_ASSETS}

RUN curl -LO https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KB_VERSION}/kubebuilder_${KB_VERSION}_linux_amd64.tar.gz \
       && tar -zxf kubebuilder_${KB_VERSION}_linux_amd64.tar.gz --strip=2 -C ${KUBEBUILDER_ASSETS} && rm -f kubebuilder_${KB_VERSION}_linux_amd64.tar.gz

RUN mkdir -p /ws

WORKDIR /ws
