FROM golang:1.14 as builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

COPY cmd/ cmd/
COPY api/ api/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o operator cmd/cockroach-operator/main.go

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest as runner

WORKDIR /
COPY --from=builder /workspace/operator .

ENTRYPOINT ["/operator"]

