/*
Copyright 2021 The Cockroach Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cockroachdb/cockroach-operator/apis/v1alpha1"
	scheme "github.com/cockroachdb/cockroach-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CrdbClustersGetter has a method to return a CrdbClusterInterface.
// A group's client should implement this interface.
type CrdbClustersGetter interface {
	CrdbClusters(namespace string) CrdbClusterInterface
}

// CrdbClusterInterface has methods to work with CrdbCluster resources.
type CrdbClusterInterface interface {
	Create(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.CreateOptions) (*v1alpha1.CrdbCluster, error)
	Update(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.UpdateOptions) (*v1alpha1.CrdbCluster, error)
	UpdateStatus(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.UpdateOptions) (*v1alpha1.CrdbCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CrdbCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CrdbClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CrdbCluster, err error)
	CrdbClusterExpansion
}

// crdbClusters implements CrdbClusterInterface
type crdbClusters struct {
	client rest.Interface
	ns     string
}

// newCrdbClusters returns a CrdbClusters
func newCrdbClusters(c *CrdbV1alpha1Client, namespace string) *crdbClusters {
	return &crdbClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the crdbCluster, and returns the corresponding crdbCluster object, and an error if there is any.
func (c *crdbClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CrdbCluster, err error) {
	result = &v1alpha1.CrdbCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdbclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CrdbClusters that match those selectors.
func (c *crdbClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CrdbClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CrdbClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested crdbClusters.
func (c *crdbClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crdbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a crdbCluster and creates it.  Returns the server's representation of the crdbCluster, and an error, if there is any.
func (c *crdbClusters) Create(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.CreateOptions) (result *v1alpha1.CrdbCluster, err error) {
	result = &v1alpha1.CrdbCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crdbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(crdbCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a crdbCluster and updates it. Returns the server's representation of the crdbCluster, and an error, if there is any.
func (c *crdbClusters) Update(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.UpdateOptions) (result *v1alpha1.CrdbCluster, err error) {
	result = &v1alpha1.CrdbCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crdbclusters").
		Name(crdbCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(crdbCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *crdbClusters) UpdateStatus(ctx context.Context, crdbCluster *v1alpha1.CrdbCluster, opts v1.UpdateOptions) (result *v1alpha1.CrdbCluster, err error) {
	result = &v1alpha1.CrdbCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crdbclusters").
		Name(crdbCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(crdbCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the crdbCluster and deletes it. Returns an error if one occurs.
func (c *crdbClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdbclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *crdbClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdbclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched crdbCluster.
func (c *crdbClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CrdbCluster, err error) {
	result = &v1alpha1.CrdbCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crdbclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
