apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: cockroach-operator
  name: cockroach-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: cockroach-operator
status:
  loadBalancer: {}
