#!/usr/bin/env bash

# Copyright 2023 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

main() {
  local template="${1}"
  local query=$(head -n1 "${template}")
  shift

  for file in "$@"; do
    # skip when content is found
    if head -n20 ${file} | grep "${query}" >/dev/null; then continue; fi

    cat "${template}" "${file}" > "${file}.mod"
    mv "${file}.mod" "${file}"
  done
}

main "$@"
