apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cockroach-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cockroach-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cockroach-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cockroach-operator
        {{- include "cockroach-operator.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cockroach-operator.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cockroach-operator
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -zap-log-level
            - {{ .Values.logLevel | quote }}
            {{- if .Values.skipWebhookConfig }}
            - -skip-webhook-config
            {{- end }}
          env:
            - name: OPERATOR_NAME
              value: cockroachdb
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.watchNamespaces }}
            - name: WATCH_NAMESPACE
              value: {{ join "," .Values.watchNamespaces | quote }}
            {{- end }}
            {{- range $version, $image := .Values.relatedImages }}
            - name: RELATED_IMAGE_COCKROACH_{{ $version | replace "." "_" | replace "-" "_" }}
              value: {{ $image | quote }}
            {{- end }}
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
        - name: cert
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}